# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations #@UnusedImport


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Common_http_demo',
        ),
        migrations.RemoveField(
            model_name='service_api',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service_base',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='service_base',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='service_base',
            name='serve_type',
        ),
        migrations.RemoveField(
            model_name='service_base',
            name='status',
        ),
        migrations.RemoveField(
            model_name='service_base',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='service_contact',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service_error_code',
            name='error_type',
        ),
        migrations.RemoveField(
            model_name='service_error_code',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service_invoke_demo',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service_others',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service_reqdemo',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service_reqfield',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service_respdemo',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service_respfield',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service_score',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service_type',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service_upgrade',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service_api',
        ),
        migrations.DeleteModel(
            name='Service_base',
        ),
        migrations.DeleteModel(
            name='Service_category',
        ),
        migrations.DeleteModel(
            name='Service_contact',
        ),
        migrations.DeleteModel(
            name='Service_error_code',
        ),
        migrations.DeleteModel(
            name='Service_error_type',
        ),
        migrations.DeleteModel(
            name='Service_invoke_demo',
        ),
        migrations.DeleteModel(
            name='Service_others',
        ),
        migrations.DeleteModel(
            name='Service_protocol',
        ),
        migrations.DeleteModel(
            name='Service_provider',
        ),
        migrations.DeleteModel(
            name='Service_reqDemo',
        ),
        migrations.DeleteModel(
            name='Service_reqField',
        ),
        migrations.DeleteModel(
            name='Service_respDemo',
        ),
        migrations.DeleteModel(
            name='Service_respField',
        ),
        migrations.DeleteModel(
            name='Service_score',
        ),
        migrations.DeleteModel(
            name='Service_status',
        ),
        migrations.DeleteModel(
            name='Service_Tag',
        ),
        migrations.DeleteModel(
            name='Service_type',
        ),
        migrations.DeleteModel(
            name='Service_upgrade',
        ),
    ]
